#!/usr/bin/expect -f
#======================================================================
#                    L E R A S E 
#                    doc: Sun Mar  7 16:18:07 2021
#                    dlm: Wed Mar 10 15:21:20 2021
#                    (c) 2021 A.M. Thurnherr
#                    uE-Info: 13 26 NIL 0 0 72 2 2 4 NIL ofnI
#======================================================================

# HISTORY:
#  Mar  8, 2021: - created
#  Mar  9, 2021: - added  $memory_empty
#  Mar 10, 2021: - renamed

source [regsub {Ldir} [exec which Ldir] {libacquire2.expect}];

log_user 0;

init_acquire;
send_user "Connecting...";
connect_to_instruments;
wakeup_instruments;

list_dir;
if {$memory_empty} {
	send_user "\nno data in instrument memory\n";
} else {
	if {[affirm "\nERASE MEMORY? (Y/n) --- timeout erases! " 10 1]} {
		send_user "Erasing memory...";
		erase_memory;
		send_user "\n";
	}
}

shutdown_instruments;
