#!/usr/bin/expect -f
#======================================================================
#                    L S T A R T 
#                    doc: Sun Mar  7 16:18:07 2021
#                    dlm: Wed Mar 10 15:21:34 2021
#                    (c) 2021 A.M. Thurnherr
#                    uE-Info: 12 28 NIL 0 0 72 2 2 4 NIL ofnI
#======================================================================

# HISTORY:
#  Mar  9, 2021: - created 
#  Mar 10, 2021: - made work

source [regsub {Ldir} [exec which Ldir] {libacquire2.expect}];

log_user 0;
init_acquire;

if {![file isfile .last_LADCP]} {							# set LADCP profile id
	exec echo 1 > .last_LADCP;
}
set profnum [expr [exec cat .last_LADCP] + 1];

if ![file isdirectory $DATA_DIRECTORY] {					# ensure data directory exists
	exec mkdir -p $DATA_DIRECTORY; 
}

set cast_dir [format %s/%03d $DATA_DIRECTORY $profnum];		# sanity check
if [file isdirectory $cast_dir] {
	send_error "ABORT: data directory $cast_dir already exists, correct .last_LADCP to proceed\n";
	exit 1;
}
	
if {$argc == 0} {											# collect CTD info (stn.cast)
	set stncast [input_stncast "CTD Station.Cast = "];
} else {
	set stncast [lindex $argv 0];
}

send_user "Connecting...";									# wake up instruments
connect_to_instruments;
wakeup_instruments;

list_dir;													# erase memory if needed/requested
if {!$memory_empty && [affirm "\nERASE MEMORY? (y/n) "]} {
	send_user "Erasing memory...";
	erase_memory;
	send_user "\n";
}
	
exec mkdir $cast_dir;										# create data directory
exec echo $profnum  > .last_LADCP;							# save current LADCP profile number

exec cp $PRIMARY_SETUP $cast_dir;							# save instrument configurations
if {[info exists SECONDARY_COMMS]} {
	exec cp $SECONDARY_SETUP $cast_dir;
}
exec echo $stncast > [format %s/CTD.station $cast_dir];		# save CTD station/cast info

send_user "Resetting instruments to factory defaults...";	# load factory defaults
load_factory_defaults;

send_user "\nSetting instrument clocks...";					# set instrument  clocks
set_clocks;

send_user "\nUploading command files";
upload_configs;

send_user "\nDone\n";

